import { createFileRoute } from '@tanstack/react-router';
import ContentPage from '@/components/heartfirst/ContentPage';
import { pageHead } from '@/lib/metadata';
export const Route = createFileRoute('/privacidad')({ head: () => pageHead("Política de privacidad"), component: Content });
function Content() { return <ContentPage title="Política de privacidad">
<section><h2>Quién es el responsable</h2><p>{"Miguel Ángel Pérez, [NIF], [dirección], miguelangel@heartfirst.es. Este proyecto está en fase de estudio: todavía no es un servicio comercial."}</p></section>
<section><h2>Para qué usamos tus datos</h2><p>{"(1) Gestionar tu inscripción en la lista de espera y avisarte de novedades. (2) Hacerte una entrevista por voz y unos cuestionarios breves, y preparar con ellos un retrato de tu personalidad y tus valores. (3) Analizar, de forma agregada, si este enfoque resulta útil y qué interés despierta. (4) Medir qué anuncios funcionan, solo si aceptas las cookies."}</p></section>
<section><h2>Qué datos tratamos</h2><p>{"Email, edad, género, el género de la persona que buscas, tu intención, tu ciudad, el audio de la entrevista y su transcripción, tus respuestas a los cuestionarios y tu valoración del retrato. Algunos son especialmente protegidos: el género que buscas puede revelar tu orientación sexual, y en la entrevista puedes mencionar datos de salud. No te preguntamos por tu ideología ni tu religión, y nunca las deducimos."}</p></section>
<section><h2>Con qué base</h2><p>{"Tu consentimiento, que das por separado para cada finalidad y para los datos especialmente protegidos. Puedes retirarlo cuando quieras, sin que afecte a lo ya hecho."}</p></section>
<section><h2>Cómo usamos la inteligencia artificial</h2><p>{"La entrevista y el retrato los prepara un sistema de IA. Antes de analizar tu texto, eliminamos nombres, lugares y cualquier dato que te identifique. La IA no toma decisiones sobre ti: el retrato es informativo y puedes pedir que lo revise una persona."}</p></section>
<section><h2>Cuánto tiempo</h2><p>{"El audio, un máximo de 7 días. La transcripción anonimizada, los cuestionarios y el retrato, 6 meses. Tu email y los datos del formulario, hasta el lanzamiento o 12 meses como máximo. Después se borran."}</p></section>
<section><h2>Con quién los compartimos</h2><p>{"Solo con los proveedores que nos ayudan a prestar el servicio, con contrato de encargado del tratamiento: base de datos en la Unión Europea (Supabase, Frankfurt), alojamiento web [proveedor], transcripción [proveedor], anonimización (Privaro), análisis por IA (Anthropic) y envío de emails [proveedor]. Si alguno trata datos fuera de la UE, lo hace con las garantías que exige la normativa europea. Nunca vendemos tus datos ni los compartimos con inversores o anunciantes."}</p></section>
<section><h2>Tus derechos</h2><p>{"Acceso, rectificación, supresión, oposición, limitación y portabilidad, escribiendo a miguelangel@heartfirst.es. Si crees que no hemos respetado tus derechos, puedes reclamar ante la Agencia Española de Protección de Datos (aepd.es)."}</p></section>
<section><h2>Menores</h2><p>{"Este estudio es solo para mayores de 35 años. Si detectamos datos de un menor, los borramos de inmediato."}</p></section>
</ContentPage>; }
