import { useEffect } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Heart, MessageCircle, ShieldCheck, EyeOff, Fingerprint, LockKeyhole, Handshake, Compass, UserCheck, Clock3, Check, Minus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import cafe from '@/assets/heartfirst-cafe.jpg';
import RegistrationForm from './RegistrationForm';
import { captureCampaign } from '@/lib/campaign';
import type { Variant } from '@/types/registration';

const reasons = [
  { icon: Heart, title: 'Juzgados por una foto', text: 'En las aplicaciones decides en un segundo, por una cara. Aquí primero conoces cómo piensa alguien, qué le importa y cómo suena su voz. La foto llega al final, cuando ya sabes a quién miras.' },
  { icon: MessageCircle, title: 'Demasiadas opciones, ningún vínculo', text: 'Mil perfiles no son mil oportunidades. Te presentamos a pocas personas, elegidas con cuidado, y te pedimos que les des tiempo.' },
  { icon: EyeOff, title: '¿Quién hay de verdad al otro lado?', text: 'Perfiles falsos, edades que no cuadran, intenciones que no se dicen. Aquí cada persona verifica su identidad y viene a lo mismo que tú: una relación estable.' },
];
const steps = [
  ['Cuéntanos quién eres', 'Una entrevista por voz de unos 20 minutos, guiada por nuestro asistente digital, a tu ritmo y desde casa. Nada de rellenar casillas sobre ti: hablas, y nosotros aprendemos cómo eres.', 'Ya disponible'],
  ['Descúbrete en tu espejo', 'Te devolvemos un retrato de cómo eres y qué te importa, con el animal que mejor te representa. Lo revisas y lo corriges: nadie sabe más de ti que tú.', 'Ya disponible'],
  ['Te presentamos a alguien', 'Pocas personas, elegidas por valores compartidos, forma de ser y manera de vincularse. Sin fotos.', 'Próximamente en Madrid'],
  ['Conoceos sin prisa', 'Una conversación guiada, con preguntas que acercan y notas de voz. Al ritmo de los dos.', 'Próximamente en Madrid'],
  ['El momento de miraros', 'Cuando los dos queréis, veis vuestras fotos a la vez. Y si hay ganas, la primera cita.', 'Próximamente en Madrid'],
];
const commitments = [
  { icon: Fingerprint, title: 'Personas reales', text: 'Cada persona verifica su identidad antes de conocer a nadie.' },
  { icon: LockKeyhole, title: 'Cero perfiles falsos', text: 'Nunca crearemos perfiles de relleno.' },
  { icon: EyeOff, title: 'Tus datos no se venden', text: 'Ni se ceden, ni hay publicidad de terceros.' },
  { icon: Heart, title: 'Siempre la verdad', text: 'Si no encontramos a alguien compatible, te lo decimos.' },
  { icon: Handshake, title: 'Sin juicios "por la cara"', text: 'Tu foto solo se ve al final, y a la vez que la de la otra persona.' },
  { icon: Compass, title: 'Nadie desaparece sin más', text: 'Cada cierre se hace con un mensaje respetuoso.' },
  { icon: UserCheck, title: 'El mismo precio para todas las personas', text: 'Sin diferencias por género ni por edad.' },
  { icon: Clock3, title: 'Libertad para irte', text: 'Te das de baja en un paso y borramos tus datos.' },
];
const faqs = [
  ['¿De verdad no voy a ver fotos?', 'No hasta el final. Primero os conocéis por lo que pensáis, lo que os importa y vuestra voz. Cuando los dos queréis, veis vuestras fotos a la vez. Lo físico importa, y por eso llega; pero llega cuando ya sabes a quién estás mirando.'],
  ['¿Y si al final no me atrae?', 'Puede pasar, y no es un fracaso: habrás conocido a alguien de verdad, y lo habrás sabido en semanas, no tras meses de citas con alguien que no te encajaba por dentro. Por eso la revelación llega tras unas semanas de conversación y no tras meses, y cerramos con respeto si alguno de los dos no sigue.'],
  ['¿Usáis inteligencia artificial?', 'Sí, como herramienta y nunca a escondidas. Un asistente digital te hace la entrevista y nos ayuda a preparar tu retrato. Antes de analizar nada eliminamos tu nombre y cualquier dato que te identifique. El retrato lo revisas tú, y las presentaciones las supervisa una persona del equipo.'],
  ['¿Qué hacéis con mis datos?', 'Usarlos solo para lo que nos autorizas. El audio se borra en un máximo de 7 días, no vendemos ni cedemos datos y puedes pedir que los borremos cuando quieras. Todo el detalle está en la política de privacidad.'],
  ['¿Para qué edades es?', 'Para personas que buscan pareja estable a partir de los 40, aunque se puede entrar desde los 35.'],
  ['¿Es para cualquier orientación?', 'Sí. Heartfirst es para cualquier persona que busque una relación estable, sea quien sea la persona que busca.'],
  ['¿Dónde funciona?', 'Empezamos en Madrid. Si vives en otra ciudad, apúntate igualmente: la lista de espera nos dice dónde abrir después.'],
  ['¿Cuánto cuesta?', 'Entrar en la lista y hacer tu entrevista es gratis. El acompañamiento tendrá un precio único, igual para todas las personas, que anunciaremos al abrir el piloto; quienes estén en la lista tendrán condiciones de fundación.'],
  ['¿Cómo sé que las personas son reales?', 'Antes de conocer a nadie, cada persona verifica su identidad con su documento y un selfie. Nunca creamos perfiles de relleno.'],
  ['¿Quién está detrás?', 'Miguel Ángel Pérez, fundador de varias empresas de tecnología de confianza, que conoce el problema desde dentro. Puedes leer su carta y escribirle directamente.'],
];
export default function LandingPage({ variant }: { variant: Variant }) {
  useEffect(() => { captureCampaign(); }, []);
  const isA = variant === 'a';
  function scrollToForm() { document.getElementById('lista-espera')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
  return <main>
    <section className={`hero ${isA ? '' : 'hero-b'}`}><img className="hero-image" src={cafe} alt="Dos tazas de café junto a una ventana de Madrid, esperando una conversación." width={1600} height={1024} fetchPriority="high" /><div className="container hero-inner"><div className="hero-copy"><h1>{isA ? <>Conócele<br />antes de <em>verle.</em></> : <>Nuestro éxito es que no vuelvas a <em>necesitarnos.</em></>}</h1><p>{isA ? 'Una nueva forma de encontrar pareja estable, donde la foto llega al final. Primero, valores, voz y conversación.' : 'Te acompañamos hasta que encuentres a alguien con quien construir. Sin suscripciones sin fin.'}</p><Button className="hero-cta" onClick={scrollToForm}>Quiero conocer Heartfirst <ArrowRight /></Button></div></div><div className="hero-footnote"><ShieldCheck size={17} /><p>Identidad verificada antes de conocer a nadie <span>·</span> Tus datos nunca se venden <span>·</span> Sin fotos hasta el final</p></div></section>
    <section className="section why-section"><div className="container"><div className="section-heading"><span className="eyebrow">Otra forma de encontrarse</span><h2>El amor no cabe en un <em>escaparate.</em></h2><p className="mt-6">Durante mucho tiempo, alguien te conocía antes de elegirte. En algún momento lo pusimos al revés. Nosotros lo volvemos a poner en su sitio.</p></div><div className="three-columns">{reasons.map(({ icon: Icon, title, text }) => <article key={title} className="why-item"><Icon size={30} strokeWidth={1.3} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section alternate"><div className="container"><div className="section-heading"><span className="eyebrow">Primero, lo que importa</span><h2>Del «quién eres» al <em>«encantado de conocerte».</em></h2></div><div className="steps">{steps.map(([title, text, status], index) => <article key={title}><span className="step-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p><span className="mt-4 block text-sm font-semibold text-terracotta-text">{status}</span></article>)}</div><div className="center-link"><Link to="/metodo">Conoce nuestro método <ArrowRight size={16} /></Link></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Con criterio y con cuidado</span><h2>No es intuición. Es lo que sabemos sobre las <em>parejas que duran.</em></h2></div><div className="two-columns science"><div><Compass size={25} className="mb-5 text-terracotta" /><h3 className="mb-4">Basado en la ciencia de las relaciones</h3><p>Décadas de investigación en psicología de pareja coinciden en algo: lo que sostiene una relación con los años son los valores compartidos, la forma de comunicarse y la manera de vincularse con el otro. Eso es lo que miramos, con métodos usados en investigación y no con un test de revista.</p><p className="mt-5">Usamos tecnología, incluida inteligencia artificial, para escuchar tus respuestas y preparar tu retrato. Pero el retrato es tuyo: lo revisas, lo corriges y nadie lo ve sin tu permiso.</p><div className="center-link"><Link to="/metodo">Conoce nuestro método <ArrowRight size={16} /></Link></div></div><div><ShieldCheck size={25} className="mb-5 text-terracotta" /><h3 className="mb-4">Tu intimidad, protegida</h3><p>Lo que nos cuentas es lo más personal que hay, y lo tratamos como tal. Cumplimos la normativa europea de protección de datos desde el primer día: antes de analizar tus respuestas eliminamos tu nombre y cualquier dato que te identifique, tu audio se borra en un máximo de 7 días y nunca vendemos ni cedemos tus datos.</p><div className="center-link"><Link to="/privacidad">Cómo protegemos tus datos <ArrowRight size={16} /></Link></div></div></div></div></section>
    <section className="section commitments-section"><div className="container"><div className="section-heading"><span className="eyebrow">Lo que no negociamos</span><h2>Ocho promesas que puedes <em>comprobar.</em></h2></div><div className="commitment-grid">{commitments.map(({ icon: Icon, title, text }) => <article key={title}><Icon size={25} strokeWidth={1.4} /><h3>{title}</h3><p>{text}</p></article>)}</div><div className="center-link"><Link to="/compromisos">Lee nuestros compromisos completos <ArrowRight size={16} /></Link></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">La honestidad, desde el principio</span><h2>Para quién no es <em>Heartfirst</em></h2></div><div className="two-columns suitability"><article><Minus size={24} /><h3>Heartfirst no es para ti si…</h3><ul className="list-disc space-y-3 pl-5 text-muted-foreground">{['buscas algo pasajero o sin compromiso', 'necesitas ver una foto antes de decidir si alguien merece tu tiempo', 'prefieres tener muchas opciones abiertas a la vez', 'no tienes unas semanas para conversar con calma', 'ahora mismo tienes pareja'].map(text => <li key={text}>{text}</li>)}</ul></article><article><Check size={24} /><h3>Está hecho para ti si…</h3><ul className="list-disc space-y-3 pl-5 text-muted-foreground">{['quieres compartir tu vida con alguien, no solo una cena', 'crees que lo que de verdad importa no cabe en una foto', 'quieres dar tiempo a alguien, y que te lo den a ti'].map(text => <li key={text}>{text}</li>)}</ul></article></div></div></section>
    <section className="section founder-section"><div className="container founder-layout"><img src="/fundador.png" alt="Miguel Ángel Pérez, fundador de Heartfirst." width={240} height={240} loading="lazy" className="object-center!" /><div><span className="eyebrow">Una carta personal</span><h2>Del fundador, <em>para ti.</em></h2><blockquote>«Durante años probé aplicaciones de citas, una tras otra, hasta que un día las borré todas y volví a conocer a las personas cara a cara. Y aun así creo que la tecnología puede ayudar, si se usa para lo contrario: dejar que conozcas a alguien antes de juzgarle. Para quienes no quieren rendirse, pero tampoco volver al escaparate, lanzo Heartfirst.»</blockquote><p>Miguel Ángel Pérez, fundador</p><div className="center-link"><Link to="/compromisos" hash="carta">Lee la carta completa <ArrowRight size={16} /></Link></div></div></div></section>
    <section className="section"><div className="container program-layout"><div><span className="eyebrow">Cómo te acompañamos</span><h2>Un acompañamiento, no una <em>suscripción.</em></h2><p>Heartfirst funciona como las agencias de pareja de siempre: te acompañamos durante 6 o 12 meses, con principio y final y un único objetivo. No pagas por mirar perfiles ni por mandar mensajes; pagas por que te acompañemos hasta conocer a alguien con quien construir.</p><h3 className="mb-4 mt-6">Qué incluye</h3><ul className="list-disc space-y-2 pl-5 text-muted-foreground">{['Tu entrevista y tu espejo, revisado contigo', 'Verificación de identidad', 'Presentaciones elegidas una a una por compatibilidad', 'Conversaciones guiadas, por escrito y por voz', 'Una persona del equipo que te acompaña todo el tiempo', 'Seguimiento después de cada primera cita'].map(text => <li key={text}>{text}</li>)}</ul><h3 className="mb-4 mt-6">Sobre el precio</h3><p>Único e igual para todas las personas. Lo anunciaremos al abrir el piloto en Madrid, y quienes estén en la lista de espera tendrán condiciones de fundación.</p><p className="mt-6 font-bold">Entrar en la lista es gratis y no te compromete a nada.</p><Button className="hero-cta" onClick={scrollToForm}>Quiero conocer Heartfirst <ArrowRight /></Button></div><div className="program-mark"><img src="/heartfirst.svg" alt="" width={100} height={100} /><span>Primero, la persona.</span></div></div></section>
    <section className="section alternate"><div className="container faq-layout"><div><span className="eyebrow">Sin dudas entre nosotros</span><h2>Preguntas <em>frecuentes</em></h2></div><Accordion type="multiple" defaultValue={['0', '1', '2', '3']}>{faqs.map(([question, answer], index) => <AccordionItem key={question} value={String(index)}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <RegistrationForm variant={variant} />
  </main>;
}
