import { useEffect } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, Heart, MessageCircle, ShieldCheck, EyeOff, Fingerprint, LockKeyhole, Handshake, Compass, Sparkles, UserCheck, Clock3, Check, Minus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import cafe from '@/assets/heartfirst-cafe.jpg';
import RegistrationForm from './RegistrationForm';
import CookieConsent from './CookieConsent';
import { captureCampaign } from '@/lib/campaign';
import type { Variant } from '@/types/registration';
const placeholder = 'Contenido pendiente de incorporar.';
export default function LandingPage({ variant }: { variant: Variant }) {
  useEffect(() => { captureCampaign(); }, []);
  const isA = variant === 'a';
  function scrollToForm() { document.getElementById('lista-espera')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
  return <main><section className={`hero ${isA ? '' : 'hero-b'}`}><img className="hero-image" src={cafe} alt="Dos tazas de café junto a una ventana de Madrid, esperando una conversación." width={1600} height={1024} fetchPriority="high" /><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow">Pareja estable a partir de los 40 · Madrid</span><h1>{isA ? <>Conócele<br />antes de <em>verle.</em></> : <>Nuestro éxito es que no vuelvas a <em>necesitarnos.</em></>}</h1><p>{isA ? 'Un programa para encontrar pareja estable donde la foto llega al final. Primero, valores, voz y conversación.' : 'Un programa para encontrar pareja estable, sin suscripciones sin fin. Te acompañamos con un único objetivo: que encuentres a alguien con quien construir.'}</p><Button className="hero-cta" onClick={scrollToForm}>Quiero conocer Heartfirst <ArrowRight /></Button></div></div><div className="hero-footnote"><ShieldCheck size={17} /><p>Identidad verificada antes de conocer a nadie <span>·</span> Tus datos nunca se venden <span>·</span> Sin fotos hasta el final</p></div></section>
  <section className="section why-section"><div className="container"><div className="section-heading"><span className="eyebrow">Otra forma de encontrarse</span><h2>Por qué <em>Heartfirst</em></h2></div><div className="three-columns">{[[Heart, 'Valores'], [MessageCircle, 'Conversación'], [EyeOff, 'La foto, al final']].map(([Icon, title], index) => { const ItemIcon = Icon as typeof Heart; return <article key={index} className="why-item"><ItemIcon size={30} strokeWidth={1.3} /><h3>{String(title)}</h3><p>{placeholder}</p></article>; })}</div></div></section>
  <section className="section alternate"><div className="container"><div className="section-heading"><span className="eyebrow">Primero, lo que importa</span><h2>Cómo <em>funciona</em></h2></div><div className="steps">{['Tu entrevista', 'Tus valores', 'La conexión', 'La conversación', 'El encuentro'].map((title, index) => <article key={title}><span className="step-number">0{index + 1}</span><h3>{title}</h3><p>{placeholder}</p></article>)}</div><div className="center-link"><Link to="/metodo">Conoce nuestro método <ArrowRight size={16} /></Link></div></div></section>
  <section className="section"><div className="container two-columns science"><div><span className="eyebrow">Con criterio y con cuidado</span><h2>Ciencia y <em>garantías</em></h2><p>{placeholder}</p></div><div className="science-items">{[[Compass, 'Un método con fundamento'], [ShieldCheck, 'Un espacio de confianza']].map(([Icon, title], index) => { const ItemIcon = Icon as typeof Heart; return <article key={index}><ItemIcon size={25} /><div><h3>{String(title)}</h3><p>{placeholder}</p></div></article>; })}</div></div></section>
  <section className="section commitments-section"><div className="container"><div className="section-heading"><span className="eyebrow">Lo que no negociamos</span><h2>Nuestros <em>compromisos</em></h2></div><div className="commitment-grid">{[Fingerprint, LockKeyhole, EyeOff, Heart, Handshake, Compass, UserCheck, Clock3].map((Icon, index) => <article key={index}><Icon size={25} strokeWidth={1.4} /><h3>Compromiso {index + 1}</h3><p>{placeholder}</p></article>)}</div><div className="center-link"><Link to="/compromisos">Nuestros compromisos, en detalle <ArrowRight size={16} /></Link></div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">La honestidad, desde el principio</span><h2>Para quién no es <em>Heartfirst</em></h2></div><div className="two-columns suitability"><article><Check size={24} /><h3>Si buscas una pareja estable</h3><p>{placeholder}</p></article><article><Minus size={24} /><h3>Si buscas algo diferente</h3><p>{placeholder}</p></article></div></div></section>
  <section className="section founder-section"><div className="container founder-layout"><img src={cafe} alt="Escena de café, marcador de imagen para la carta del fundador." width={1600} height={1024} loading="lazy" /><div><span className="eyebrow">Una carta personal</span><h2>Del fundador, <em>para ti.</em></h2><blockquote>«El extracto de la carta del fundador se incorporará aquí.»</blockquote><p>Miguel Ángel Pérez <span>— Fundador de Heartfirst</span></p></div></div></section>
  <section className="section"><div className="container program-layout"><div><span className="eyebrow">Acompañarte, no retenerte</span><h2>El <em>programa</em></h2><p>{placeholder}</p><Button className="hero-cta" onClick={scrollToForm}>Quiero conocer Heartfirst <ArrowRight /></Button></div><div className="program-mark"><img src="/heartfirst.svg" alt="" width={100} height={100} /><span>Primero, la persona.</span></div></div></section>
  <section className="section alternate"><div className="container faq-layout"><div><span className="eyebrow">Sin dudas entre nosotros</span><h2>Preguntas <em>frecuentes</em></h2></div><Accordion type="single" collapsible>{['¿En qué consiste Heartfirst?', '¿Por qué la foto llega al final?', '¿Para quién está pensado el programa?', '¿Qué ocurre después de apuntarme?', '¿Cómo se protegen mis datos?'].map((question, index) => <AccordionItem key={question} value={String(index)}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{placeholder}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  <RegistrationForm variant={variant} /><CookieConsent /></main>;
}
